# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(3rdparty/|cmake/ECM/|/cmake/KDAB/)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: check-json
#- repo: https://github.com/pre-commit/mirrors-clang-format
#  rev: v13.0.0
#  hooks:
#  - id: clang-format
- repo: https://github.com/PyCQA/pylint
  rev: v2.15.2
  hooks:
  - id: pylint
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
  - id: codespell
